name: Run Wordle Bot

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: 'Wordle Result'
        required: true
        type: string
  repository_dispatch:
    types: discord-wordle-message

jobs:
  run-wordle-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'

    - name: Install dependencies
      run: bun install

    - name: Run script
      run: bun run process-wordle-result.ts
      env:
        PARSED_WORDLE: ${{ github.event.inputs.client_payload }}
