name: Run Wordle Bot

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: 'Wordle Result'
        required: true
  repository_dispatch:
    types: discord-wordle-message

jobs:
  run-wordle-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Run Wordle Bot
        run: bun run process-wordle-result.ts
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PARSED_WORDLE: ${{ github.event.client_payload }}
