name: Run Wordle Bot

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: 'Wordle Result'
        required: true
        type: string
  repository_dispatch:
    types: discord-wordle-message

jobs:
  run-wordle-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'

    - name: Install dependencies
      run: bun install

    - name: Run script
      run: bun run process-wordle-result.ts
      env:
        PARSED_WORDLE: ${{ github.event.inputs.client_payload }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
        APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
        APPWRITE_COLLECTION_ID: ${{ secrets.APPWRITE_COLLECTION_ID }}
        APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
        APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
        USER_TAGGING_ENABLED: ${{ secrets.USER_TAGGING_ENABLED }}
